export enum TitlePage {
  PRODUCT = 'Món ăn',
  CATEGORY = 'Danh mục',
  USER = 'Người dùng',
  ORDER = 'Đơn hàng',
  EMPLOYEE = 'Nhân viên',
  DEFAULT = 'Empty',
}

export enum EnumPage {
  AUDIT = 'audit',
  PARTNER = 'partner',
  PROPOSAL = 'proposal',
  INSURER = 'insurer',
  CUSTOMER = 'customer',
  BENEFIT = 'benefit',
  COVERAGE = 'coverage',
  LIMIT = 'limit',
  CLAUSE = 'clause',
  DOCUMENT = 'document',
  RELATIONSHIP = 'relationship',
  DEDUCTIBLE = 'deductible',
  WAITING_PERIOD = 'waiting-period',
  RISK = 'risk',
  QUESTION = 'question',
  USER = 'user',
  ORDER = 'order',
  CATEGORY = 'category',
  PRODUCT = 'product',
  EMPLOYEE = 'employee',
  DEFAULT = 'default',
}
