export enum TitlePage {
  AUDIT = 'Audit Logs Manager',
  PARTNER = 'Partner Manager',
  PRODUCT = 'Quản lý Món ăn',
  PROPOSAL = 'Proposal Manager',
  INSURER = 'Insurer Manager',
  CATEGORY = 'Category Manager',
  CUSTOMER = 'Customer Manager',
  BENEFIT = 'Benefit Manager',
  COVERAGE = 'Coverage Manager',
  LIMIT = 'Limit Manager',
  CLAUSE = 'Clause Manager',
  DOCUMENT = 'Document Manager',
  RELATIONSHIP = 'Relationship Management',
  RELATIONSHIP_CREATE = 'Create Relationship',
  RELATIONSHIP_EDIT = 'Edit Relationship',
  DEDUCTIBLE = 'Deductible Manager',
  WAITING_PERIOD = 'Waiting Period Manager',
  RISK = 'Risk Manager',
  QUESTION = 'Question Manager',
  USER = 'Quản lý Người dùng',
  DEFAULT = 'Empty',
}

export enum EnumPage {
  AUDIT = 'audit',
  PARTNER = 'partner',
  PRODUCT = 'product',
  PROPOSAL = 'proposal',
  INSURER = 'insurer',
  CATEGORY = 'category',
  CUSTOMER = 'customer',
  BENEFIT = 'benefit',
  COVERAGE = 'coverage',
  LIMIT = 'limit',
  CLAUSE = 'clause',
  DOCUMENT = 'document',
  RELATIONSHIP = 'relationship',
  DEDUCTIBLE = 'deductible',
  WAITING_PERIOD = 'waiting-period',
  RISK = 'risk',
  QUESTION = 'question',
  USER = 'user',
  DEFAULT = 'default',
}
